  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: '"C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\MSBuild.exe"'
  BL_PATH: '"C:\Program Files (x86)\GeneXus\GeneXus17"'
  WORKING_DIR: '"D:\\AzureCheckouts\\$(KB_ALIAS)"'
  KB_ALIAS: '"ActualizacionAmbiente2"'
  GXSERVER_URL: '"https://sandform.genexusserver.com/kbs"'
  GXSERVER_USER: '"gxtechnical\crown081"'
  GXSERVER_PASS: $(password)
  RUN: $(Build.BuildId)

trigger:
- main

pool:
  name: GeneXusBuilder

steps:
- script: $(MSBUILD) $(BL_PATH)\AzureCICD.msbuild -target:CreateOrUpdateKB /p:WorkingDirectory=$(WORKING_DIR);CreateDbInKbFolder=True;DbaseName=$(KB_ALIAS);DbaseUseIntegratedSecurity=True;ServerUrl=$(GXSERVER_URL);ServerKbAlias=$(KB_ALIAS);ServerUsername=$(GXSERVER_USER);ServerPassword=$(GXSERVER_PASS)
  displayName: 'Create or Update KB'

- script: $(MSBUILD) $(BL_PATH)\teamdev.Msbuild -target:Build /p:WorkingDirectory=$(WORKING_DIR)
  displayName: 'Build KB'
