    # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  #Pipeline config variables:
  #$(POOL) - The variable Pool contains the name of the Agent Pool created for the project in Azure DevOps

  #Environment variables: 
  #$(TARGETPATH) - The variable TARGETPATH contains the value assigned in the Knowledge Base for the 'Target Path' property at the environment level.
  KB_PATH: $(WORKING_DIR)\$(KB_ALIAS)
  
  #KB Building variables:
  #KB_ALIAS: $(kbalias)
  #GXSERVER_URL: $(serverurl)
  #GXSERVER_USER: $(serveruser)
  #GXSERVER_PASS: $(password)
  #KBENVIRONMENT: $(environment)
  #KBGENERATOR: $(generator)
  #FORCE_REBUILD: $(forceRebuild)
  
  #Deploy variables:
  #PUBLISH_SETTINGS: $(azurePublish)
  #DEPLOYMENT_UNIT: $(deploymentUnit)
  #DEPLOY_NAME: $(deploymentUnit)$(Build.BuildNumber)
  #APPLICATION_KEY: $(encriptKey)
  
  #Code versioning variables:
  #GIT_USER: $(gituser)
  #GIT_PASSWORD: $(gitpassword) #This could alternatively be a PAT
  #GIT_REPO: $(gitrepo)
  #GIT_BRANCH: $(gitbranch) #Branch must exist. Content will be overwritten

# Scheduled triggers. Can also be setup through UI, which takes precendence.
schedules:
  - cron: "*/10 * * * *"
    displayName: Custom time trigger
    branches:
      include:
        - main
    always: false

trigger:
  - main

pool:
  name: $(POOL)

jobs:
  - job: CheckoutOrUpdate
    condition: always()
    steps:
      - script: >
         
          $(MSBUILD) "$(BL_PATH)\AzureCICD.msbuild" -target:CreateOrUpdateKB /p:WorkingDirectory=$(KB_PATH) /p:CreateDbInKbFolder=True
          /p:DbaseName=$(KB_ALIAS) /p:DbaseUseIntegratedSecurity=True /p:ServerUrl=$(GXSERVER_URL) /p:ServerKbAlias=$(KB_ALIAS) 
          /p:ServerUsername=$(GXSERVER_USER) /p:ServerPassword=$(GXSERVER_PASS)
          
          set /p updateCount=<"$(KB_PATH)\updateCount.txt"

          echo ##vso[task.setvariable variable=updateCount;isOutput=true]%updateCount%
        name: CreateOrUpdateKB

  - job: SetActiveEnvironment
    dependsOn: CheckoutOrUpdate
    condition:  always()
    steps:
      - script: >
          $(MSBUILD) /verbosity:detailed "$(BL_PATH)\AzureCICD.Msbuild" -target:SetActiveEnvironment /p:WorkingDirectory=$(KB_PATH) /p:EnvironmentName=$(ENVIRONMENTNAME) /p:PropertyValue
              echo ##vso[task.setvariable variable=PropertyValue;isOutput=true]$(TARGETPATH)
              echo ##vso[task.setvariable variable=TARGETPATH;isOutput=true]$(TARGETPATH)
              echo ##vso[task.setvariable variable=PropertyValue;isOutput=true]$(PropertyValue)
              echo ##vso[task.setvariable variable=TARGETPATH;isOutput=true]$(PropertyValue)
            echo $(TARGETPATH) $TARGETPATH $env:TARGETPATH Here   PropertyValue $(PropertyValue) $PropertyValue  $env:PropertyValue
          
            echo "OLA KE ASE"      $(TargetPath) $TARGETPATH $env:TARGETPATH PropertyValue $(PropertyValue) $PropertyValue  $env:PropertyValue
        name: SetActiveEnvironment

  - job: BuildAndDeploy
    dependsOn: SetActiveEnvironment
    condition: or(and(succeeded(), gt(dependencies.CheckoutOrUpdate.outputs['CreateOrUpdateKB.updateCount'], '0')),eq(variables['FORCE_REBUILD'], 'true'))
    steps:
      - script: >
          echo $(TARGETPATH) $TARGETPATH $env:TARGETPATH Here   PropertyValue $(PropertyValue) $PropertyValue  $env:PropertyValue
          rmdir $(KB_PATH)\$env:TARGETPATH /s /q
        condition: eq(variables['FORCE_REBUILD'], 'true')
        name: CleanBuildDir
      - script: $(MSBUILD) /verbosity:detailed "$(BL_PATH)\AzureCICD.Msbuild" -target:Build /p:AppDB=$(DATABASENAME) /p:SQLInstance=$(DB_SERVERNAME) /p:IncludeFrontendObjects=false /p:IncludeSDSamples=false /p:UpdateMode="never" /p:ForceRebuild=$(FORCE_REBUILD)
        name: BuildKB
 
      - script: >
          $(MSBUILD) /verbosity:detailed "$(BL_PATH)\deploy.msbuild" /t:CreateDeploy /p:KBPath=$(KB_PATH);KBEnvironment=$(KBENVIRONMENT);DeploymentUnit=$(DEPLOYMENT_UNIT) 
          /p:ProjectName=$(DEPLOY_NAME) /p:TargetId="AZURE" /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)"
          /p:DEPLOY_TARGETS="$(BL_PATH)\DeploymentTargets\Azure\azure.targets" 
          /p:DeployFullPath="$(KB_PATH)\$(TargetPath)\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:WebSourcePath="$(KB_PATH)\$(TargetPath)\web" /p:GX_PROGRAM_DIR="$(BL_PATH)" 
          /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)"
        name: CreateDeploy

      - script: >  
          $(MSBUILD)  /verbosity:detailed  /ToolsVersion:4.0 "$(KB_PATH)\$(TargetPath)\web\$(DEPLOY_NAME).gxdproj" /t:CreatePackage 
          /p:GX_PROGRAM_DIR="$(BL_PATH)" /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)"
        name: CreatePackage

      - script: >
          $(MSBUILD)  /verbosity:detailed  "$(BL_PATH)\DeploymentTargets\Azure\deploy.msbuild" /t:Deploy 
          /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)" /p:APPLICATION_NAME="$(DEPLOY_NAME)" 
          /p:DEPLOY_PATH="$(KB_PATH)\$(TargetPath)\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:GX_PROGRAM_DIR="$(BL_PATH)" /p:DeploySource="$(KB_PATH)\$(TargetPath)\Deploy\AZURE\$(DEPLOY_NAME).zip" 
          /p:CreateCloudPackage="false" /p:KBPath=$(KB_PATH) /p:KBEnvironment="$(KBENVIRONMENT)" /p:KBVersion="ActualizacionAmbiente2" 
          /p:DeploymentUnit="$(DEPLOYMENT_UNIT)" /p:ProjectName="$(DEPLOY_NAME)" /p:TargetId="AZURE" /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)"
          /p:DEPLOY_TARGETS="$(BL_PATH)\DeploymentTargets\Azure\azure.targets" 
          /p:DeployFullPath="$(KB_PATH)\$(TargetPath)\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:WebSourcePath="$(KB_PATH)\$(TargetPath)\web" /p:GENERATOR="$(KBGENERATOR)"
        name: DeploytoWebApp
  
  - job: CloneOrPull
    dependsOn: BuildAndDeploy
    condition: succeeded()
    steps:
      - script: |
          IF EXIST "$(GIT_BRANCH)" (
            cd $(GIT_BRANCH)
            git pull
          ) ELSE (
            git clone https://$(GIT_USER):$(GIT_PASSWORD)@$(GIT_REPO) $(WORKING_DIR)\$(GIT_BRANCH)
          )
        workingDirectory: $(WORKING_DIR)
        name: CloneOrPull
      
  - job: PushSourcesToGit
    dependsOn: CloneOrPull
    condition: succeeded()
    steps:
      - script: >
          xcopy /E /I /Y "$(KB_PATH)\$(TARGETPATH)" "$(WORKING_DIR)\$(GIT_BRANCH)"

          cd $(GIT_BRANCH)

          git add *
        
          git commit -m "Commit build $(Build.BuildNumber)"

          git push -u origin $(GIT_BRANCH)
        workingDirectory: $(WORKING_DIR)
        name: CommitPush
